#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
sudo cp /etc/hosts ~/modified_hosts
sed -i 's/^127.*$/127\.0\.0\.2 localhost/' ~/modified_hosts
echo "8.8.8.8	facebook.com" >> ~/modified_hosts
sudo cp -f ~/modified_hosts /etc/hosts
